services:
  web:
    build: .
    ports:
      - "8080:3350"
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

###docker exec -it git-server sh
# git config --global user.name "Lim Vi Shean" 
# git config --global user.email "2302054@sit.singaporetech.edu.sg" 