services:
  web:
    build: .
    ports:
      - "8080:3350"
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
  sonarqube:
    image: sonarqube:lts-community
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
###docker exec -it git-server sh
# git config --global user.name "Lim Vi Shean" 
# git config --global user.email "2302054@sit.singaporetech.edu.sg" 